# Generated by Django 3.1.7 on 2021-05-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210509_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Org',
        ),
    ]
