# Generated by Django 3.1.7 on 2021-05-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210509_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
