# Generated by Django 3.1.7 on 2021-05-09 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20210509_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgs',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orgs',
            name='username',
        ),
        migrations.AddField(
            model_name='orgs',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key', to=settings.AUTH_USER_MODEL),
        ),
    ]
