# Generated by Django 3.1.7 on 2021-05-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210509_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orgs',
        ),
    ]
