# Generated by Django 3.1.7 on 2021-05-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210509_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='info',
            field=models.CharField(default='lol idk', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='name',
            field=models.CharField(default='name', max_length=64),
            preserve_default=False,
        ),
    ]
