# Generated by Django 3.1.7 on 2021-05-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210511_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='website',
            field=models.CharField(default='unavailable', max_length=64),
            preserve_default=False,
        ),
    ]
