# Generated by Django 3.1.7 on 2021-05-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_org_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='metadata',
            field=models.CharField(default='yes', max_length=128),
            preserve_default=False,
        ),
    ]
