# Generated by Django 3.1.7 on 2021-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_org_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='metadata',
            field=models.JSONField(),
        ),
    ]
