# Generated by Django 3.1.7 on 2021-05-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210521_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='metadata',
            field=models.CharField(max_length=128),
        ),
    ]
