# Generated by Django 3.1.7 on 2021-06-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210521_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='image',
            field=models.ImageField(default='booba', upload_to=''),
            preserve_default=False,
        ),
    ]
