# Generated by Django 3.1.7 on 2021-06-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_org_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='image',
        ),
        migrations.AddField(
            model_name='org',
            name='logo',
            field=models.ImageField(default='image', upload_to='logos'),
            preserve_default=False,
        ),
    ]
