# Generated by Django 3.1.7 on 2021-07-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210609_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='logo',
        ),
    ]
