# Generated by Django 3.1.7 on 2021-07-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_org_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='logo',
            field=models.ImageField(default='media/logos/default.png', upload_to='media/logos'),
        ),
    ]
