# Generated by Django 3.1.7 on 2021-07-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_org_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='logo',
            field=models.ImageField(default='logos/default.png', upload_to='logos'),
        ),
    ]
