# Generated by Django 3.1.7 on 2021-07-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210710_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='info',
            field=models.TextField(),
        ),
    ]
